/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Be sure your device is not in standby mode.": { "en": "Be sure your device is not in standby mode.",     "de": "Vergewissern Sie sich, dass sich Ihr Gerät nicht im Standby-Modus befindet.", "ru": "Убедитесь, что ваше устройство не находится в режиме ожидания.", "pt": "Certifique-se de que seu dispositivo não esteja no modo de espera.", "nl": "Zorg ervoor dat uw apparaat niet in de standby-modus staat.", "fr": "Assurez-vous que votre appareil n'est pas en mode veille.", "it": "Assicurati che il tuo dispositivo non sia in modalità standby.", "es": "Asegúrese de que su dispositivo no esté en modo de espera.", "pl": "Upewnij się, że urządzenie nie znajduje się w trybie gotowości."},
    "Select one": {                                  "en": "Select one",                                      "de": "Wähle eins",                                      "ru": "Выберите один",                                   "pt": "Selecione um",                                    "nl": "Kies een",                                        "fr": "Sélectionnez un",                                 "it": "Seleziona uno",                                   "es": "Seleccione uno",                                  "pl": "Wybierz jeden"},
    "Nothing found": {                               "en": "Nothing found",                                   "de": "Nichts gefunden",                                 "ru": "Ничего не найдено",                               "pt": "Nada encontrado",                                 "nl": "Niets gevonden",                                  "fr": "Rien n'a été trouvé",                             "it": "Non abbiamo trovato nulla",                       "es": "Nada Encontrado",                                 "pl": "Nic nie znaleziono"},
    "Main settings": {                               "en": "Main settings",                                   "de": "Haupteinstellungen",                              "ru": "Основные параметры",                              "pt": "Configurações principais",                        "nl": "Belangrijkste instellingen",                      "fr": "Réglages principaux",                             "it": "Impostazioni principali",                         "es": "Ajustes principales",                             "pl": "Ustawienia główne"},
    "Advanced settings": {                           "en": "Advanced settings",                               "de": "Erweiterte Einstellungen",                        "ru": "Расширенные настройки",                           "pt": "Configurações avançadas",                         "nl": "Geavanceerde instellingen",                       "fr": "Réglages avancés",                                "it": "Impostazioni avanzate",                           "es": "Ajustes avanzados",                               "pl": "Zaawansowane ustawienia"},
    "IP-Address": {                                  "en": "IP-Address",                                      "de": "IP Adresse",                                      "ru": "Айпи адрес",                                      "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP"},
    "IP-Address of your player": {                   "en": "IP-Address of your player",                       "de": "IP-Adresse Ihres Players",                        "ru": "IP-адрес вашего плеера",                          "pt": "Endereço IP do seu player",                       "nl": "IP-adres van uw speler",                          "fr": "Adresse IP de votre lecteur",                     "it": "Indirizzo IP del tuo lettore",                    "es": "Dirección IP de tu reproductor",                  "pl": "Adres IP odtwarzacza"},
    "Search": {                                      "en": "Search",                                          "de": "Suche",                                           "ru": "Поиск",                                           "pt": "Procurar",                                        "nl": "Zoeken",                                          "fr": "Chercher",                                        "it": "Ricerca",                                         "es": "Buscar",                                          "pl": "Szukaj"},
    "Found devices": {                               "en": "Found devices",                                   "de": "Gefundene Geräte",                                "ru": "Найденные устройства",                            "pt": "Dispositivos encontrados",                        "nl": "Gevonden apparaten",                              "fr": "Appareils trouvés",                               "it": "Dispositivi trovati",                             "es": "Dispositivos encontrados",                        "pl": "Znaleziono urządzenia"},
    "Poll interval (ms)": {                          "en": "Poll interval (ms)",                              "de": "Abfrageintervall (ms)",                           "ru": "Интервал опроса (мс)",                            "pt": "Intervalo de pesquisa (ms)",                      "nl": "Poll-interval (ms)",                              "fr": "Intervalle de sondage (ms)",                      "it": "Intervallo di polling (ms)",                      "es": "Intervalo de sondeo (ms)",                        "pl": "Interwał ankiety (ms)"},
    "Interval between commands (ms)": {              "en": "Interval between commands (ms)",                  "de": "Intervall zwischen Befehlen (ms)",                "ru": "Интервал между командами (мс)",                   "pt": "Intervalo entre comandos (ms)",                   "nl": "Interval tussen opdrachten (ms)",                 "fr": "Intervalle entre les commandes (ms)",             "it": "Intervallo tra i comandi (ms)",                   "es": "Intervalo entre comandos (ms)",                   "pl": "Interwał między poleceniami (ms)"},
};